"""Generate mnemonics for all NREMT skill sheets using the Claude API."""
import json, os, re, anthropic

API_KEY = os.environ.get("ANTHROPIC_API_KEY")
if not API_KEY:
    raise RuntimeError("Set ANTHROPIC_API_KEY in your environment before running this script.")

client = anthropic.Anthropic(api_key=API_KEY)

with open("data.json") as f:
    data = json.load(f)

def ask(prompt):
    msg = client.messages.create(
        model="claude-opus-4-7",
        max_tokens=600,
        messages=[{"role": "user", "content": prompt}]
    )
    return msg.content[0].text.strip()

def section_names(sheet):
    return [s["name"] for s in sheet["sections"] if s.get("header") or len(sheet["sections"]) == 1]

def step_texts(section):
    out = []
    for s in section["steps"]:
        # Use the top-level text; substeps share the parent step's slot
        out.append(s["text"])
    return out

results = {}

for sheet in data["sheets"]:
    sid = sheet["id"]
    print(f"Generating mnemonics for {sid} — {sheet['shortTitle']}...")
    entry = {"sections": None, "steps": {}}

    secs = [s for s in sheet["sections"] if s.get("header")]
    if len(secs) > 1:
        names = [s["name"] for s in secs]
        prompt = (
            f"You are helping an EMT student memorize the section order of the NREMT skill sheet "
            f"\"{sheet['title']}\".\n\n"
            f"The sections in order are:\n"
            + "\n".join(f"{i+1}. {n}" for i, n in enumerate(names))
            + "\n\nCreate ONE short, vivid mnemonic sentence or acronym (≤15 words) that helps "
            "remember this exact order. Output ONLY the mnemonic — no explanation, no label."
        )
        entry["sections"] = ask(prompt)
        print(f"  Sections mnemonic: {entry['sections']}")

    for sec in sheet["sections"]:
        steps = step_texts(sec)
        if len(steps) < 2:
            continue
        prompt = (
            f"You are helping an EMT student memorize the steps in the \"{sec['name']}\" section "
            f"of the NREMT \"{sheet['title']}\" skill sheet.\n\n"
            f"The steps in order are:\n"
            + "\n".join(f"{i+1}. {s}" for i, s in enumerate(steps))
            + "\n\nCreate ONE short, vivid mnemonic sentence or acronym (≤15 words) that helps "
            "remember this exact sequence. Output ONLY the mnemonic — no explanation, no label."
        )
        entry["steps"][sec["name"]] = ask(prompt)
        print(f"  [{sec['name']}]: {entry['steps'][sec['name']]}")

    results[sid] = entry

js = "// Auto-generated by generate_mnemonics.py — edit via the UI, not here.\n"
js += "(function(global){\n"
js += "  global.NREMT_MNEMONICS = " + json.dumps(results, indent=2) + ";\n"
js += "})(window);\n"

with open("js/mnemonics.js", "w") as f:
    f.write(js)

print("\nDone! Written to js/mnemonics.js")
