/**
 * medical_conditions.js – EMT medical condition signs/symptoms reference data.
 *
 * Sets window.MEDICAL_CONDITIONS = [{
 *   id, name, category, compareGroup, onset,
 *   keyDifferentiator, signs[], distinguishing[],
 *   criticalFindings[], treatment[], compareDimensions{}
 * }]
 *
 * Sources: Brady Emergency Care (Limmer/O'Keefe), NIH StatPearls,
 * ACEP Clinical Policies, NAEMSP Position Statements, study.com NREMT modules.
 */
(function (global) {
  global.MEDICAL_CONDITIONS = [

    // ── DIABETIC EMERGENCIES ──────────────────────────────────────────────

    {
      id: "hypoglycemia",
      name: "Hypoglycemia",
      category: "Diabetic Emergencies",
      compareGroup: "diabetic",
      onset: "Rapid (minutes to hours)",
      keyDifferentiator: "Moist/clammy skin, diaphoresis, rapid onset",
      signs: [
        "Altered mental status, confusion, irritability",
        "Shakiness, weakness, tremors",
        "Diaphoresis (excessive sweating)",
        "Tachycardia",
        "Moist, clammy skin",
        "Anxiety, nervousness",
        "Normal to rapid respirations",
        "Pale skin",
      ],
      distinguishing: [
        "Moist, clammy skin — opposite of the dry skin seen in hyperglycemia",
        "Rapid onset (minutes to hours, not days)",
        "History of missed meal, excess insulin, or unusual exertion",
        "No fruity breath odor",
        "Responds to glucose administration (diagnostic/therapeutic)",
      ],
      criticalFindings: [
        "Altered mental status in a known diabetic",
        "Rapid deterioration with diaphoresis and moist skin",
        "Unresponsive patient with diabetic history",
      ],
      treatment: [
        "Administer oral glucose if patient is conscious and able to swallow",
        "Do NOT give glucose if airway is compromised (aspiration risk)",
        "Treat empirically when blood glucose cannot be confirmed and AMS is present",
        "Rapid transport if no improvement after glucose administration",
        "Reassess mental status frequently",
      ],
      compareDimensions: {
        onset: "Rapid (minutes to hours)",
        skin: "Moist, clammy, diaphoretic",
        breath: "Normal",
        respirations: "Normal to rapid",
        keySign: "Diaphoresis (sweating)",
        history: "Missed meal, too much insulin, excess exertion",
      },
    },

    {
      id: "hyperglycemia",
      name: "Hyperglycemia",
      category: "Diabetic Emergencies",
      compareGroup: "diabetic",
      onset: "Gradual (hours to days)",
      keyDifferentiator: "Dry skin, fruity breath, Kussmaul respirations (in DKA)",
      signs: [
        "Polydipsia (excessive thirst)",
        "Polyuria (frequent urination)",
        "Dry skin, dry mucous membranes",
        "Warm, flushed skin",
        "Altered mental status, confusion",
        "Nausea, vomiting, abdominal cramping",
        "Fruity/acetone breath odor (in DKA)",
        "Kussmaul respirations — rapid, deep breathing (in DKA)",
        "Dehydrated appearance",
        "Weakness, fatigue",
      ],
      distinguishing: [
        "Dry skin and mucous membranes — dehydrated appearance",
        "Gradual onset over hours to days (not sudden)",
        "Fruity/acetone breath odor indicates diabetic ketoacidosis (DKA)",
        "Kussmaul respirations (rapid, deep, labored) in DKA",
        "History of missed insulin doses, illness, or dietary excess",
      ],
      criticalFindings: [
        "Fruity breath + Kussmaul respirations = DKA — medical emergency",
        "Severely altered mental status with dehydration signs",
      ],
      treatment: [
        "Supportive care — do NOT administer glucose",
        "High-flow oxygen if respiratory distress present",
        "Rapid transport for definitive care (IV fluids, insulin)",
        "Airway management if mental status severely altered",
        "Monitor vital signs frequently",
      ],
      compareDimensions: {
        onset: "Gradual (hours to days)",
        skin: "Dry, warm, flushed",
        breath: "Fruity/acetone odor (in DKA)",
        respirations: "Kussmaul (rapid, deep) in DKA; otherwise normal",
        keySign: "Fruity breath / dry skin / polydipsia",
        history: "Missed insulin, illness, dietary excess",
      },
    },

    // ── CARDIAC ───────────────────────────────────────────────────────────

    {
      id: "ami",
      name: "AMI (Heart Attack)",
      category: "Cardiac",
      compareGroup: "cardiac_dyspnea",
      onset: "Sudden or gradual",
      keyDifferentiator: "Chest pressure/squeezing, diaphoresis, radiation to left arm or jaw",
      signs: [
        "Chest pain — pressure, squeezing, heaviness, tightness",
        "Pain radiation to left arm, jaw, neck, back, or shoulder",
        "Diaphoresis (cold sweat)",
        "Shortness of breath (dyspnea)",
        "Nausea, vomiting",
        "Lightheadedness, syncope, near-syncope",
        "Anxiety, sense of impending doom",
        "Tachycardia, possible arrhythmia",
        "Pale, cool, clammy skin",
        "Fatigue, weakness",
      ],
      distinguishing: [
        "Classic: chest pressure/squeezing lasting >10 minutes",
        "Left arm or jaw radiation is highly specific for cardiac origin",
        "Diaphoresis with chest pain strongly suggests AMI",
        "Atypical presentations common in women, elderly, and diabetics (dyspnea, nausea, or fatigue alone)",
        "Symptoms NOT relieved by rest or antacids",
        "Risk factors: smoking, hypertension, diabetes, family history, obesity",
      ],
      criticalFindings: [
        "Chest pain + diaphoresis + left arm radiation",
        "Chest discomfort + dyspnea + pale clammy skin",
        "Any chest discomfort in patient with known cardiac history",
        "Silent MI: diabetic/elderly with unexplained dyspnea or weakness alone",
      ],
      treatment: [
        "HIGH PRIORITY — call for ALS if available",
        "Position of comfort — usually sitting upright",
        "Supplemental oxygen if SpO2 <94%",
        "Aspirin 324 mg (chewed, not swallowed whole) per protocol if not contraindicated",
        "Rapid transport — note exact symptom onset time (thrombolytic window critical)",
        "Monitor for arrhythmias; be prepared to perform CPR/AED",
      ],
      compareDimensions: {
        onset: "Sudden or gradual; may last hours",
        dyspnea: "Common, may be only symptom (atypical)",
        skin: "Pale, cool, clammy with diaphoresis",
        edema: "Not present (unless concurrent CHF)",
        keySign: "Chest pressure + diaphoresis + radiation",
        history: "Cardiac risk factors; symptoms unrelieved by rest",
      },
    },

    {
      id: "chf",
      name: "CHF (Congestive Heart Failure)",
      category: "Cardiac",
      compareGroup: "cardiac_dyspnea",
      onset: "Gradual (hours to days)",
      keyDifferentiator: "Crackles/rales + JVD + peripheral edema — the classic triad",
      signs: [
        "Dyspnea (shortness of breath), worse lying flat (orthopnea)",
        "Crackles/rales on lung auscultation",
        "Jugular venous distention (JVD) — swollen neck veins",
        "Peripheral edema — swollen ankles, shins, legs",
        "Tachypnea (rapid breathing)",
        "Productive cough, possibly with pink frothy sputum",
        "Cool, clammy skin",
        "Possible wheezing ('cardiac asthma')",
        "Fatigue, weakness",
        "Tachycardia",
      ],
      distinguishing: [
        "Classic triad: crackles + JVD + bilateral leg edema",
        "Orthopnea — patient cannot lie flat, sleeps on multiple pillows",
        "Bilateral crackles (fluid in lungs from failed left ventricle)",
        "Pink frothy sputum is a late, severe sign (pulmonary edema)",
        "No smoking history required; associated with hypertension or prior MI",
        "JVD distinguishes from COPD (COPD rarely causes JVD unless advanced)",
      ],
      criticalFindings: [
        "JVD + crackles + bilateral peripheral edema",
        "Pink frothy sputum — severe pulmonary edema, imminent respiratory failure",
        "Worsening orthopnea with tachycardia and hypoxia",
      ],
      treatment: [
        "HIGH PRIORITY — rapid transport",
        "Sit patient upright (Fowler or semi-Fowler position) — reduces preload",
        "High-flow oxygen; consider CPAP per protocol",
        "Do NOT lay flat — worsens dyspnea",
        "IV access, medication per ALS protocol",
        "Monitor SpO2 continuously",
      ],
      compareDimensions: {
        onset: "Gradual (hours to days)",
        breathSounds: "Crackles/rales (bilateral, fluid)",
        skin: "Cool, clammy",
        JVD: "Present — key distinguishing finding",
        edema: "Bilateral peripheral edema (ankles, shins)",
        keySign: "Crackles + JVD + leg edema triad",
        smokingHistory: "Not required; linked to hypertension/MI",
      },
    },

    // ── RESPIRATORY – OBSTRUCTIVE ─────────────────────────────────────────

    {
      id: "copd",
      name: "COPD Exacerbation",
      category: "Respiratory",
      compareGroup: "obstructive",
      onset: "Gradual worsening from a chronic baseline",
      keyDifferentiator: "Heavy smoking history, chronic productive cough, barrel chest",
      signs: [
        "Wheezing (may be diminished in severe obstruction)",
        "Dyspnea — worse than baseline",
        "Chronic productive cough (often purulent during exacerbation)",
        "Barrel chest appearance",
        "Pursed-lip breathing",
        "Use of accessory muscles",
        "Tachypnea, tachycardia",
        "Cyanosis possible",
        "Altered mental status with severe hypercapnia",
        "Possible low-grade fever if infection-triggered",
      ],
      distinguishing: [
        "Heavy smoking history (current or former) — almost universal",
        "Chronic productive cough ('smoker's cough') is the patient's baseline",
        "Barrel chest from chronic air trapping",
        "Symptoms are worse than usual (exacerbation), not new",
        "Limited bronchodilator response — does NOT fully clear with treatment",
        "No JVD or peripheral edema (unless cor pulmonale develops)",
      ],
      criticalFindings: [
        "Altered mental status + hypoxia in known COPD patient",
        "Silent chest (no audible wheeze) — severe obstruction, near-respiratory failure",
        "SpO2 <88% with worsening level of consciousness",
      ],
      treatment: [
        "Controlled oxygen therapy (maintain SpO2 88–92% per protocol — hypoxic drive concern)",
        "Bronchodilators (albuterol/ipratropium) if protocol allows",
        "Position of comfort — sitting upright preferred",
        "CPAP/BiPAP per ALS protocol for severe exacerbations",
        "Rapid transport if altered mental status or no improvement",
      ],
      compareDimensions: {
        onset: "Gradual; worsens from chronic baseline",
        breathSounds: "Wheezing (may be absent in severe); diminished",
        skin: "Cyanosis possible; warm",
        JVD: "Absent unless cor pulmonale",
        edema: "Absent unless advanced disease",
        cough: "Chronic productive (purulent in exacerbation)",
        keySign: "Barrel chest + smoking history + chronic productive cough",
        smokingHistory: "Almost always present",
        reversibility: "Limited — does not fully resolve with bronchodilators",
      },
    },

    {
      id: "asthma",
      name: "Asthma Exacerbation",
      category: "Respiratory",
      compareGroup: "obstructive",
      onset: "Acute (minutes to hours), often triggered",
      keyDifferentiator: "Bilateral wheeze, identifiable trigger, REVERSIBLE with bronchodilators",
      signs: [
        "Bilateral wheezing (prominent, expiratory)",
        "Dyspnea, chest tightness",
        "Dry cough (may be the only symptom in mild attack)",
        "Tachypnea, tachycardia",
        "Use of accessory muscles",
        "Anxiety, agitation",
        "Prolonged expiratory phase",
        "Decreased SpO2 in moderate–severe attack",
        "Tripod positioning",
      ],
      distinguishing: [
        "Identifiable trigger: allergen, exercise, cold air, viral URI, stress",
        "REVERSIBLE — significant improvement with bronchodilators",
        "Often younger patients (can affect any age)",
        "Normal between attacks — no chronic baseline symptoms",
        "No significant smoking history",
        "History of asthma, allergies, or eczema common",
      ],
      criticalFindings: [
        "Silent chest (absent wheeze) — severe bronchospasm, near-respiratory failure",
        "Altered mental status + dyspnea in known asthmatic",
        "No improvement after bronchodilator use — requires rapid transport",
        "SpO2 <90% with accessory muscle use",
      ],
      treatment: [
        "High-flow oxygen",
        "Bronchodilators — albuterol MDI or nebulizer per protocol (KEY treatment)",
        "Position of comfort — sitting upright",
        "Calm, reassuring approach (anxiety worsens bronchospasm)",
        "Rapid transport if no improvement or silent chest",
        "ALS backup for epinephrine if severe and unresponsive",
      ],
      compareDimensions: {
        onset: "Acute (minutes to hours); triggered",
        breathSounds: "Bilateral wheezing (expiratory); clears with treatment",
        skin: "Normal; cyanosis only if severe",
        JVD: "Absent",
        edema: "Absent",
        cough: "Dry, episodic",
        keySign: "Bilateral wheeze + trigger + reverses with bronchodilators",
        smokingHistory: "Not required; usually absent",
        reversibility: "REVERSIBLE — clears significantly with bronchodilators",
      },
    },

    // ── RESPIRATORY – ACUTE ───────────────────────────────────────────────

    {
      id: "pulmonary_embolism",
      name: "Pulmonary Embolism (PE)",
      category: "Respiratory – Acute",
      compareGroup: "pulmonary_acute",
      onset: "Sudden (minutes)",
      keyDifferentiator: "Sudden dyspnea + tachycardia + tachypnea, NO fever, pleuritic chest pain",
      signs: [
        "Sudden onset dyspnea (shortness of breath)",
        "Pleuritic chest pain (sharp, worse with breathing)",
        "Tachycardia (HR often >100 bpm)",
        "Tachypnea (RR often >20)",
        "Hypoxemia (decreased SpO2)",
        "Anxiety, sense of doom",
        "Syncope or near-syncope (massive PE)",
        "Hemoptysis — coughing blood (uncommon but specific)",
        "Unilateral leg swelling (DVT sign)",
        "Pale, clammy skin",
      ],
      distinguishing: [
        "Sudden onset (minutes) without prior respiratory illness",
        "NO fever — key differentiator from pneumonia",
        "Normal or near-normal breath sounds despite severe dyspnea",
        "Tachycardia + tachypnea disproportionate to exam findings",
        "Risk factors: recent immobilization, surgery, malignancy, long travel, pregnancy",
        "Unilateral leg swelling or tenderness (DVT source)",
      ],
      criticalFindings: [
        "Sudden unexplained dyspnea + tachycardia in patient with DVT risk factors",
        "Syncope + dyspnea (massive PE with cardiovascular collapse)",
        "Hemoptysis + pleuritic chest pain",
      ],
      treatment: [
        "HIGH PRIORITY — rapid transport for definitive imaging and anticoagulation",
        "High-flow oxygen (hypoxemia may be severe)",
        "Position of comfort — usually sitting upright",
        "Monitor closely for shock development",
        "ALS backup if hemodynamic instability present",
      ],
      compareDimensions: {
        onset: "Sudden (minutes)",
        breathSounds: "Normal initially",
        fever: "Absent — key differentiator",
        cough: "Dry; possible hemoptysis",
        keySign: "Sudden dyspnea + tachycardia, no fever, DVT risk",
        breathSoundsSymmetry: "Equal (bilateral)",
      },
    },

    {
      id: "pneumothorax",
      name: "Pneumothorax",
      category: "Respiratory – Acute",
      compareGroup: "pulmonary_acute",
      onset: "Sudden (minutes)",
      keyDifferentiator: "Unilateral absent/decreased breath sounds, unilateral sharp chest pain",
      signs: [
        "Sudden sharp pleuritic chest pain (unilateral)",
        "Dyspnea (shortness of breath)",
        "Absent or markedly decreased breath sounds on affected side",
        "Tachycardia, tachypnea",
        "Decreased SpO2",
        "Subcutaneous emphysema (air under skin — 'crunching' feel)",
        "Tension signs: hypotension + JVD + tracheal deviation away from affected side",
      ],
      distinguishing: [
        "UNILATERAL decreased/absent breath sounds — single most important finding",
        "Sudden onset without prior respiratory illness or fever",
        "Often young, tall, thin males (spontaneous) or follows trauma",
        "Tension pneumothorax: shock + JVD + absent breath sounds = emergency",
        "Tracheal deviation is a LATE and unreliable sign — do not wait for it",
      ],
      criticalFindings: [
        "Absent unilateral breath sounds + hypotension + JVD = TENSION PNEUMOTHORAX",
        "Rapidly worsening respiratory distress after thoracic trauma",
        "Unilateral chest injury + decreasing SpO2",
      ],
      treatment: [
        "High-flow oxygen; position of comfort",
        "Rapid transport",
        "TENSION PNEUMOTHORAX: needle decompression at 2nd intercostal space, midclavicular line — if trained and protocol allows",
        "Seal open chest wounds with occlusive dressing (3-sided)",
        "Reassess frequently — tension pneumothorax can develop after initial assessment",
      ],
      compareDimensions: {
        onset: "Sudden (minutes)",
        breathSounds: "UNILATERAL absent/decreased (hallmark finding)",
        fever: "Absent",
        cough: "Dry",
        keySign: "Unilateral absent breath sounds + chest pain",
        breathSoundsSymmetry: "UNEQUAL — defines pneumothorax",
      },
    },

    {
      id: "pneumonia",
      name: "Pneumonia",
      category: "Respiratory – Acute",
      compareGroup: "pulmonary_acute",
      onset: "Gradual (hours to days)",
      keyDifferentiator: "Fever + productive cough + crackles — gradual onset",
      signs: [
        "Fever (often >101°F / 38.3°C)",
        "Productive cough with sputum (yellow, green, rust-colored, or blood-tinged)",
        "Dyspnea, tachypnea",
        "Pleuritic chest pain",
        "Crackles/rales on auscultation",
        "Chills, rigors",
        "Malaise, fatigue, body aches",
        "Decreased SpO2 possible",
        "Tachycardia",
        "Possible wheezing",
      ],
      distinguishing: [
        "Fever is the hallmark — absent in PE and pneumothorax",
        "Productive cough with purulent or colored sputum",
        "Gradual onset over hours to days (not sudden like PE or pneumothorax)",
        "Crackles on lung exam (focal or lobar)",
        "Often preceded by URI or flu-like illness",
        "Elderly patients may present with fever as the only prominent symptom",
      ],
      criticalFindings: [
        "Fever + productive cough + dyspnea + altered mental status (sepsis risk)",
        "Elderly or immunocompromised patient with acute fever and confusion",
        "SpO2 <90% with tachypnea (high-priority transport)",
      ],
      treatment: [
        "Supplemental oxygen for hypoxemia",
        "Position of comfort — usually sitting upright",
        "Monitor vital signs; watch for septic shock progression",
        "Transport (definitive antibiotics require hospital care)",
        "Keep patient warm; infection control precautions",
      ],
      compareDimensions: {
        onset: "Gradual (hours to days)",
        breathSounds: "Crackles/rales (focal or lobar)",
        fever: "PRESENT — key differentiator",
        cough: "Productive (purulent/colored sputum)",
        keySign: "Fever + productive cough + crackles",
        breathSoundsSymmetry: "May be unilateral or bilateral crackles",
      },
    },

    // ── NEUROLOGICAL ─────────────────────────────────────────────────────

    {
      id: "stroke",
      name: "Stroke (CVA)",
      category: "Neurological",
      compareGroup: "neuro",
      onset: "Sudden (seconds to minutes)",
      keyDifferentiator: "FAST: Facial droop, Arm weakness, Speech difficulty — symptoms PERSIST",
      signs: [
        "Facial drooping — unilateral, asymmetric smile",
        "Arm weakness/drift — unilateral",
        "Speech difficulty — slurred, garbled, or absent",
        "Sudden severe headache (hemorrhagic stroke)",
        "Sudden vision loss or blurred vision (monocular or field cut)",
        "Sudden confusion, disorientation",
        "Sudden dizziness, loss of balance, ataxia",
        "Unilateral numbness or weakness",
        "Unilateral paralysis",
        "Altered level of consciousness",
      ],
      distinguishing: [
        "Symptoms PERSIST and do not resolve (unlike TIA)",
        "FAST exam positive: facial droop, arm drift, speech difficulty",
        "Any new focal neurological deficit = stroke until proven otherwise",
        "Ischemic (87%): blood clot — treatment window 3–4.5 hours from onset",
        "Hemorrhagic (13%): sudden severe 'thunderclap' headache common",
        "Note exact time of symptom onset — critical for hospital treatment decisions",
      ],
      criticalFindings: [
        "Any FAST-positive finding",
        "Sudden unilateral weakness + speech difficulty + facial droop",
        "Sudden 'worst headache of my life' (suggests subarachnoid hemorrhage)",
      ],
      treatment: [
        "TIME IS BRAIN — every minute counts; rapid transport to stroke center",
        "Note exact onset time (required for thrombolytic eligibility)",
        "Airway management — aspiration risk if altered consciousness",
        "Do NOT give food or fluids (aspiration risk)",
        "Position: 30° head elevation if tolerated",
        "Monitor vital signs; control hypertension only per medical direction",
        "ALS backup",
      ],
      compareDimensions: {
        onset: "Sudden (seconds to minutes)",
        symptomDuration: "PERSISTENT — does not resolve",
        FASTexam: "Positive (facial droop, arm drift, speech)",
        headache: "Possible (severe = hemorrhagic)",
        keySign: "Persistent focal neuro deficit — FAST positive",
        urgency: "Immediate — stroke center transport",
      },
    },

    {
      id: "tia",
      name: "TIA (Mini-Stroke)",
      category: "Neurological",
      compareGroup: "neuro",
      onset: "Sudden (seconds to minutes)",
      keyDifferentiator: "Stroke-like symptoms that FULLY RESOLVE within 24 hours (typically minutes)",
      signs: [
        "Transient facial drooping (resolved by time of assessment)",
        "Transient arm weakness or drift (now resolved)",
        "Transient speech difficulty (now resolved)",
        "Transient monocular blindness",
        "Transient confusion or disorientation",
        "Transient unilateral numbness or weakness",
        "Normal neurological exam at time of arrival if resolved",
      ],
      distinguishing: [
        "Symptoms FULLY RESOLVE — patient appears completely normal when assessed",
        "Episodes typically last minutes to <1 hour (by definition <24 hours)",
        "FAST findings may be absent if symptoms resolved before arrival",
        "TIA is a WARNING SIGN — 10–15% have a major stroke within 3 months",
        "Cannot be distinguished from stroke in the field — treat as stroke",
        "Definitive TIA vs stroke requires MRI imaging at hospital",
      ],
      criticalFindings: [
        "History of transient focal neurological deficit, even if now resolved",
        "Patient reporting 'episode of weakness/speech problem that went away'",
      ],
      treatment: [
        "Transport urgently — TIA carries high risk for imminent stroke",
        "Do NOT reassure patient that 'it went away' — still serious",
        "Note onset and resolution times",
        "Same transport priority as active stroke",
        "Supportive care; monitor for symptom recurrence",
      ],
      compareDimensions: {
        onset: "Sudden (seconds to minutes)",
        symptomDuration: "TRANSIENT — resolves completely (<24 h, usually minutes)",
        FASTexam: "May be negative if resolved at assessment",
        headache: "Usually absent",
        keySign: "Stroke symptoms that resolved — still treat as emergency",
        urgency: "Urgent — high near-term stroke risk",
      },
    },

    {
      id: "seizure",
      name: "Seizure / Post-Ictal State",
      category: "Neurological",
      compareGroup: "neuro",
      onset: "Sudden (seizure); gradual recovery (post-ictal phase 5–30+ min)",
      keyDifferentiator: "Witnessed convulsions; post-ictal: drowsy + confused + gradually improving",
      signs: [
        "Tonic-clonic: full body stiffness then rhythmic jerking",
        "Loss of consciousness during seizure",
        "Incontinence (bowel or bladder)",
        "Tongue biting — LATERAL biting is 100% specific for true seizure",
        "Eyes rolled back",
        "Foaming at mouth",
        "Post-ictal: drowsiness, lethargy, confusion",
        "Post-ictal: gradual return to baseline over 5–30 minutes",
        "Post-ictal: muscle soreness, headache",
        "Elevated heart rate and blood pressure",
      ],
      distinguishing: [
        "Lateral tongue biting is 100% specific for true generalized seizure",
        "Post-ictal state: confusion that gradually and progressively improves",
        "Witnessed convulsive movements (tonic-clonic, focal, or absence)",
        "Incontinence is common (unlike syncope)",
        "Status epilepticus: seizure >5 minutes or repeated seizures without recovery",
        "Pseudo-seizure: no lateral tongue bite, quick recovery, clear emotional triggers",
      ],
      criticalFindings: [
        "Seizure >5 minutes (status epilepticus) — immediate ALS",
        "First-time seizure in any patient",
        "Seizure in a pregnant patient",
        "No recovery of consciousness between back-to-back seizures",
        "Trauma from fall during seizure",
      ],
      treatment: [
        "Protect from injury — do NOT restrain; move hazards away",
        "Do NOT place objects in the mouth",
        "Recovery position (lateral) after seizure ends — aspiration risk",
        "High-flow oxygen",
        "ALS backup for status epilepticus (benzodiazepines)",
        "Allow post-ictal recovery — do NOT aggressively rouse",
        "Rapid transport if: first seizure, status epilepticus, pregnancy, or trauma",
      ],
      compareDimensions: {
        onset: "Sudden convulsion; post-ictal recovery 5–30 min",
        symptomDuration: "Seizure 30 s to 5 min; post-ictal up to hours",
        FASTexam: "May have transient weakness post-ictally",
        headache: "Common post-ictally",
        keySign: "Lateral tongue bite + incontinence + gradual post-ictal recovery",
        urgency: "Urgent if first seizure, status, or trauma",
      },
    },

    // ── ALLERGIC / IMMUNE ─────────────────────────────────────────────────

    {
      id: "allergic_reaction",
      name: "Mild Allergic Reaction",
      category: "Allergic / Immune",
      compareGroup: "allergic",
      onset: "Variable (minutes to hours after exposure)",
      keyDifferentiator: "Localized hives/itching with STABLE vital signs and NO airway compromise",
      signs: [
        "Localized itching (pruritus)",
        "Hives (urticaria), rash",
        "Localized angioedema (mild swelling)",
        "Watery eyes, nasal congestion",
        "Mild wheezing possible",
        "Normal blood pressure",
        "Normal to mildly elevated heart rate",
        "Alert, normal mental status",
      ],
      distinguishing: [
        "Symptoms relatively isolated — not multi-system",
        "Vital signs stable — NO hypotension",
        "No airway compromise — no stridor, no facial/oral swelling",
        "No signs of shock",
        "May improve spontaneously or with antihistamines",
        "Key: presence of any airway involvement or hypotension upgrades to ANAPHYLAXIS",
      ],
      criticalFindings: [
        "Any development of throat/tongue swelling, stridor, or hypotension → upgrade to anaphylaxis",
        "Rapid progression of symptoms despite stable initial presentation",
      ],
      treatment: [
        "Diphenhydramine (Benadryl) per protocol",
        "Remove/avoid the allergen if identifiable",
        "Supportive care and monitoring",
        "Transport for observation",
        "Reassess frequently — may deteriorate to anaphylaxis",
      ],
      compareDimensions: {
        onset: "Variable (minutes to hours)",
        airway: "Clear — no compromise",
        bloodPressure: "Normal",
        skinFindings: "Localized hives/itching",
        shockSigns: "Absent",
        keySign: "Localized reaction, stable vitals, no airway involvement",
        epinephrine: "NOT indicated",
      },
    },

    {
      id: "anaphylaxis",
      name: "Anaphylaxis",
      category: "Allergic / Immune",
      compareGroup: "allergic",
      onset: "Rapid (minutes after exposure)",
      keyDifferentiator: "Multi-system: airway compromise OR hypotension + allergic exposure → EPINEPHRINE",
      signs: [
        "Stridor (upper airway swelling)",
        "Severe wheezing, bronchospasm",
        "Severe dyspnea, respiratory distress",
        "Facial/oral/tongue angioedema",
        "Hypotension (shock)",
        "Tachycardia, weak thready pulse",
        "Syncope or near-syncope",
        "Generalized urticaria (hives)",
        "Flushing, pruritus",
        "Nausea, vomiting, diarrhea, abdominal cramping",
        "Altered mental status",
        "Cyanosis possible",
      ],
      distinguishing: [
        "Multi-system involvement — respiratory + cardiovascular + skin",
        "HYPOTENSION or AIRWAY COMPROMISE present (key gates for diagnosis)",
        "Rapid onset within minutes of exposure",
        "Facial/oral swelling distinguishes from mild allergic reaction",
        "NO absolute contraindication to epinephrine in anaphylaxis",
        "May occur even without prior allergic history",
      ],
      criticalFindings: [
        "Hypotension + respiratory compromise + allergic exposure = ANAPHYLAXIS",
        "Stridor (laryngeal edema) — airway may close rapidly",
        "Facial/tongue swelling + wheezing + tachycardia",
      ],
      treatment: [
        "EPINEPHRINE IMMEDIATELY — IM injection to lateral mid-thigh",
        "Adult: 0.3 mg epinephrine (EpiPen); Pediatric (>15 kg): 0.15 mg (EpiPen Jr)",
        "Hold auto-injector in place for 10 seconds",
        "Repeat every 5–10 min if symptoms persist",
        "High-flow oxygen",
        "Supine position with legs elevated if hypotensive (unless dyspnea worsens in supine)",
        "Rapid transport",
        "Diphenhydramine IM/IV as secondary — does NOT replace epinephrine",
      ],
      compareDimensions: {
        onset: "Rapid (minutes)",
        airway: "COMPROMISED — stridor, angioedema",
        bloodPressure: "HYPOTENSION (shock)",
        skinFindings: "Generalized hives + facial swelling",
        shockSigns: "Present — tachycardia, hypotension, AMS",
        keySign: "Airway compromise OR hypotension with allergic exposure",
        epinephrine: "REQUIRED — first-line treatment",
      },
    },

    // ── SHOCK ──────────────────────────────────────────────────────────────

    {
      id: "hypovolemic_shock",
      name: "Hypovolemic Shock",
      category: "Shock",
      compareGroup: "shock",
      onset: "Variable (rapid if hemorrhagic)",
      keyDifferentiator: "Obvious fluid loss (bleeding, burns, dehydration) with pale/cool/clammy shock signs",
      signs: [
        "Tachycardia (early compensatory sign)",
        "Pale, cool, clammy skin",
        "Tachypnea",
        "Thirst (if conscious)",
        "Anxiety, restlessness",
        "Altered mental status (late)",
        "Hypotension (late — compensatory mechanisms mask initially)",
        "Weak, rapid pulse",
        "Delayed capillary refill",
        "Obvious bleeding or fluid loss history",
      ],
      distinguishing: [
        "Clear cause: external hemorrhage, internal bleeding, severe burns, vomiting/diarrhea",
        "Responds to fluid resuscitation (improving mental status and vital signs)",
        "No pulmonary edema (dry lungs)",
        "No cardiac history",
        "Hypotension is a LATE sign — tachycardia comes first",
      ],
      criticalFindings: [
        "Obvious hemorrhage + tachycardia + altered mental status",
        "Severe burns or dehydration with hypotension",
        "Hypotension + tachycardia + pale skin = decompensated shock",
      ],
      treatment: [
        "CONTROL BLEEDING FIRST — direct pressure, tourniquet if indicated",
        "Trendelenburg position (legs elevated) if no spinal injury",
        "High-flow oxygen",
        "Rapid transport — IV access en route, not before",
        "Keep patient warm (prevent hypothermia)",
        "Splint fractures to minimize blood loss from bone ends",
      ],
      compareDimensions: {
        cause: "Blood/fluid loss",
        heartRate: "TACHYCARDIA",
        skin: "Pale, cool, clammy",
        lungsounds: "Clear",
        JVD: "Absent",
        keySign: "Obvious fluid loss + tachycardia + pale clammy skin",
      },
    },

    {
      id: "cardiogenic_shock",
      name: "Cardiogenic Shock",
      category: "Shock",
      compareGroup: "shock",
      onset: "Variable",
      keyDifferentiator: "Heart failure signs: pulmonary edema + shock + cardiac history",
      signs: [
        "Tachycardia (rapid weak pulse)",
        "Pale, cool, clammy skin",
        "Tachypnea",
        "Hypotension",
        "Altered mental status",
        "Pulmonary edema signs (crackles, pink frothy sputum)",
        "JVD possible (right heart failure)",
        "Dyspnea",
        "Possible chest pain if concurrent MI",
      ],
      distinguishing: [
        "Pulmonary edema present (crackles, frothy sputum) — fluid backs up from failing heart",
        "History of cardiac disease, MI, arrhythmia, or heart failure",
        "Does NOT respond well to IV fluids (may worsen pulmonary edema)",
        "JVD may be present (right ventricular failure)",
      ],
      criticalFindings: [
        "Shock signs + crackles/pulmonary edema + cardiac history",
        "Shock + chest pain (concurrent AMI causing pump failure)",
      ],
      treatment: [
        "HIGH PRIORITY — rapid transport",
        "High-flow oxygen",
        "Semi-Fowler position (30–45°) — do NOT lay flat (worsens pulmonary edema)",
        "Do NOT give excessive IV fluids",
        "ALS for inotropes and rhythm management",
      ],
      compareDimensions: {
        cause: "Heart pump failure",
        heartRate: "TACHYCARDIA (bradycardia if arrhythmia)",
        skin: "Pale, cool, clammy",
        lungsounds: "CRACKLES (pulmonary edema)",
        JVD: "May be present",
        keySign: "Pulmonary edema + shock + cardiac history",
      },
    },

    {
      id: "septic_shock",
      name: "Septic Shock",
      category: "Shock",
      compareGroup: "shock",
      onset: "Gradual (hours to days of illness before shock)",
      keyDifferentiator: "Fever + infection source + shock signs (may appear warm/flushed early)",
      signs: [
        "Fever (classic) — may be absent in severe sepsis or elderly",
        "Tachycardia",
        "Tachypnea",
        "Hypotension (refractory to fluids in late sepsis)",
        "Initially warm/flushed skin (early distributive phase)",
        "Progresses to pale/cool/clammy (late)",
        "Altered mental status (confusion, delirium — especially in elderly)",
        "Identifiable infection source (productive cough, dysuria, wound, abdominal pain)",
        "Rapid deterioration despite initial treatment",
      ],
      distinguishing: [
        "FEVER differentiates from other shock types (not present in hypovolemic/cardiogenic)",
        "Identifiable infection source is key clue",
        "May present with warm, flushed skin early (vasodilatory phase)",
        "Often in immunocompromised, elderly, or chronically ill patients",
        "AMS may be the primary presentation in elderly (no obvious infection sign)",
      ],
      criticalFindings: [
        "Fever + shock signs + infection source",
        "Elderly patient with new confusion + fever (even subtle)",
        "Shock refractory to IV fluid resuscitation",
      ],
      treatment: [
        "Rapid transport",
        "High-flow oxygen",
        "IV fluid resuscitation (large volume)",
        "Keep warm if hypothermic",
        "ALS for vasopressors if refractory to fluids",
      ],
      compareDimensions: {
        cause: "Systemic infection",
        heartRate: "TACHYCARDIA",
        skin: "Early: warm/flushed; Late: pale/cool/clammy",
        lungsounds: "Variable (may have pneumonia crackles if lungs are source)",
        JVD: "Absent",
        keySign: "Fever + infection source + shock",
      },
    },

    {
      id: "neurogenic_shock",
      name: "Neurogenic Shock",
      category: "Shock",
      compareGroup: "shock",
      onset: "After spinal cord injury",
      keyDifferentiator: "BRADYCARDIA + warm dry skin in a trauma patient with spinal injury — unique among shock types",
      signs: [
        "BRADYCARDIA (slow heart rate) — hallmark finding unique to neurogenic shock",
        "Hypotension",
        "Warm, dry, flushed skin (vasodilation — NOT cool/clammy)",
        "Loss of sensation below injury level",
        "Paralysis or paresis below injury level",
        "Priapism (uncontrolled erection) — specific for spinal cord injury",
        "Inability to regulate body temperature",
        "History of significant spinal trauma",
      ],
      distinguishing: [
        "BRADYCARDIA is the key distinguishing feature from ALL other shock types",
        "Warm, DRY skin — opposite of the cool/clammy skin in other shock",
        "Clear history of spinal trauma (cervical or high thoracic)",
        "Neurological deficits below level of injury",
        "Priapism is specific for spinal cord injury",
      ],
      criticalFindings: [
        "Bradycardia + hypotension in trauma patient = suspect neurogenic shock",
        "Spinal injury + warm skin + slow pulse (triad)",
        "Paralysis below injury + cardiovascular instability",
      ],
      treatment: [
        "Spinal motion restriction",
        "High-flow oxygen",
        "Supine with legs elevated (if no thoracic injury worsens breathing)",
        "ALS for vasopressors and atropine (bradycardia treatment)",
        "IV fluid resuscitation (moderate)",
        "Rapid transport to trauma center",
        "Keep warm — loss of thermoregulation",
      ],
      compareDimensions: {
        cause: "Spinal cord injury (loss of sympathetic tone)",
        heartRate: "BRADYCARDIA — unique among shock types",
        skin: "WARM, dry, flushed — unique among shock types",
        lungsounds: "Clear",
        JVD: "Absent",
        keySign: "Bradycardia + warm dry skin + spinal trauma",
      },
    },

  ];
})(window);
